INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Superman: Action Comics', 12.99, '2022-07-11', 'C', 'http://10.0.2.2:8080/api/file/image/BOOK-COMIC-1000.jpg', 'The House of Kent, Superman, Superboy, Supergirl, the Legion of Super-Heroes’ Brainiac 5, and Young Justice’s Conner Kent must all unite to face an enemy from another dimension unleashed by the Invisible Mafia! This kind of power can lay waste to an entire family of super-people! All of this plus the future of the Daily Planet revealed!');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Batman: The Silver Age Omnibus Vol. 1', 99.99, '2022-06-12', 'C', 'http://10.0.2.2:8080/api/file/image/BOOK-COMIC-1001.jpg', 'The Caped Crusader is known for protecting the streets of Gotham from the villains who wish to cause harm. Follow along on some of his most adventurous tales in Batman: The Silver Age Omnibus Vol. 1 collecting Batman #101-116');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('The Fifth Science', 29.99, '2022-07-16', 'F', 'http://10.0.2.2:8080/api/file/image/BOOK-FICTION-1002.jpg', 'The Fifth Science is a collection of 12 stories, beginning at the start of the Galactic Human Empire and following right through to its final days. We’ll see some untypical things along the way, meet some untypical folk: galactic lighthouses from the distant future, alien tombs from the distant past, murderers, emperors, archaeologists and drunks; mad mathematicians attempting to wake the universe itself up.And when humans have fallen back into savagery, when the secrets of space folding and perfect wisdom are forgotten, we’ll attend the empire’s deathbed, hold its hand as it goes. Unfortunately that may well only be the beginning.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('The Summer House', 15.00, '2022-07-21', 'R', 'http://10.0.2.2:8080/api/file/image/BOOK-ROMANTIC-1003.jpg', 'Just when true happiness seems within reach, Callie and Olivia find a diary full of secrets... secrets that stretch across the island, and have the power to turn lives upside down. As Callie reads, she unravels a mystery that makes her heart drop through the floor. Will Callie and Luke be pulled apart by the storm it unleashes, or can true love save them?');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('The Art of Computer Programming', 187.99, '2022-05-25', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1004.jpg', 'These four books comprise what easily could be the most important set of information on any serious programmer’s bookshelf.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Python Programming for Beginners : The Ultimate Guide for Beginners', 21.99, '2022-04-17', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1005.jpg', 'Python is a high-level interpreted programming language that is used throughout the world for general-purpose programming. It is an open-source programming language licensed by both the Free Software Foundation (FSF) and Open-Source Initiative (OSI). Like some other programming languages, its source code is also available under the GNU General Public License (GPL). Throughout this book, we will be focusing more on the Python 3.x version, which is the latest and is currently in active development.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('The Self-Taught Programmer: The Definitive Guide to Programming', 21.87, '2022-01-28', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1006.jpg', 'This book is not just about learning to program; although you will learn to code. If you want to program professionally, it is not enough to learn to code; that is why, in addition to helping you learn to program, I also cover the rest of the things you need to know to program professionally that classes and books don''t teach you. "The Self-taught Programmer" is a roadmap, a guide to take you from writing your first Python program, to passing your first technical interview.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Computer Programming: The Bible: Learn from the basics to advanced', 14.95, '2022-02-10', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1007.jpg', 'Are you ready to learn and start programming with any language in less than 12 hours? The world of technology is changing and those who know how to handle it and who have the most knowledge about it are the ones who will get ahead. If you are a beginner who is interested in learning more and getting ahead, then this guidebook is the one for you.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Effective C: An Introduction to Professional C Programming', 35.01, '2022-08-22', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1008.jpg', 'Effective C will teach you how to write professional, secure, and portable C code that will stand the test of time and help strengthen the foundation of the computing world.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Head First Design Patterns: Building Extensible and Maintainable OOP', 32.43, '2022-02-19', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1009.jpg', 'If you''ve read a Head First book, you know what to expect: a visually rich format designed for the way your brain works. With Head First Design Patterns, 2E you''ll learn design principles and patterns in a way that won''t put you to sleep, so you can get out there to solve software design problems and speak the language of patterns with others on your team.');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Beginning Programming All-in-One Desk Reference For Dummies', 32.89, '2022-03-11', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1010.jpg', 'Beginning Programming All In One Desk Reference For Dummies shows you how to decide what you want your program to do, turn your instructions into “machine language” that the computer understands, use programming best practices, explore the “how” and “why” of data structuring, and more. You’ll even get a look into various applications like database management, bioinformatics, computer security, and artificial intelligence. Soon you’ll realize that — wow! You’re a programmer!');
INSERT INTO product(title, amount, `date`, category, image_url, description)
    VALUES ('Machine Learning: 4 Books in 1: An Overview for Beginners to Master', 35.01, '2023-01-25', 'P', 'http://10.0.2.2:8080/api/file/image/BOOK-PROGRAMMING-1011.jpg', 'Created with the beginner in mind, this powerful bundle delves into the fundamentals behind Python and machine learning, from basic code and mathematical formulas to complex neural networks and ensemble modeling. Inside, you’ll discover everything you need to know to get started with Python and machine learning and begin your journey to success!');

INSERT INTO role(name) values ('USER'),('ADMIN');

insert into user(username,password,email) values ('ray','$2a$12$yrqpXaFZTUXIHkriRkWEu.DiCGPMPj1JKjYEhN3Iqf4mrVRjgJxNK','ray@email.com'), ('user','$2a$12$MGOF3pyaPnHMhDGzPL/zzONLYM2Ui6oRvVVXtbPaBnIh1XSB/0b/2','user@email.com'), ('admin','$2a$12$MGOF3pyaPnHMhDGzPL/zzONLYM2Ui6oRvVVXtbPaBnIh1XSB/0b/2','admin@email.com');

insert into user_role(user_id,role_id) values (1,1),(1,2),(2,1),(3,1),(3,2);
